### ISSUE TITLE
Custom swipe card config incorrect error

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#122]
<img width="1116" alt="Screen Shot 2022-01-31 at 8 35 28 AM" src="https://user-images.githubusercontent.com/3034555/151803107-e3817497-774b-4125-a74a-ee21d791044c.png">

Hi I followed all the step-by-step instructions to install HKI, but I can't figure out how to get rid of this error.

**Comment by jimz011** [comment]
Add at least one notification

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: David Nestico ***@***.***>
Sent: Monday, January 31, 2022 2:37:28 PM
To: jimz011/homekit-infused ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jimz011/homekit-infused] Custom swipe card config incorrect error (Issue #122)


[Screen Shot 2022-01-31 at 8 35 28 AM]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3034555%2F151803107-e3817497-774b-4125-a74a-ee21d791044c.png&data=04%7C01%7C%7C9e7eb3feebc447d45d9d08d9e4bed358%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637792330497258527%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9jPIn4xhbqstPHcpa4Qry9zaVODocweP8FxGfS%2FKHp4%3D&reserved=0>

Hi followed all the step by step instructions to install HKI, but I can't figure out how to get rid of this error.

**Comment by dnestico** [comment]
<img width="1153" alt="Screen Shot 2022-01-31 at 5 28 49 PM" src="https://user-images.githubusercontent.com/3034555/151883697-d8305f97-4e12-4ac5-a276-7490ca9d416a.png">
 Thanks for your response, but now I'm getting this error with HKI and I really am lost and don't know what to do, please help, I'm just trying to get HomeKit like interface for my homeassistant. 

**LOG:**

Logger: homeassistant.components.websocket_api.http.connection
Source: hki-base/base.yaml:1190
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:30:01 AM (3 occurrences)
Last logged: 9:34:34 AM

[547609286736] Error handling message: Unknown error
[547331770400] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 188, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 207, in _load_config
    config = load_yaml(self.path, Secrets(Path(self.hass.config.config_dir)))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 111, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 123, in parse_yaml
    yaml.load(content, Loader=lambda stream: SafeLineLoader(stream, secrets))
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 253, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, ldr.secrets, args=args), ldr, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/config/hki-base/base.yaml", line 1190, in top-level template code
    {% for device in content.entities %}
TypeError: 'NoneType' object is not iterable
