### ISSUE TITLE
Error loading UI

### ISSUE THREAD

**Issue by dnestico** [jimz011/homekit-infused#123]
So I followed all of the instructions step by step and while customizing my Home room this suddenly happened and I can't figure it out. Please help I am fairly new to this.

**ERROR LOG:**

Logger: homeassistant.components.websocket_api.http.connection
Source: hki-base/base.yaml:1190
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:30:01 AM (3 occurrences)
Last logged: 9:34:34 AM

[547609286736] Error handling message: Unknown error
[547331770400] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
result = await func(hass, connection, msg, config)
File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
return await config.async_load(msg["force"])
File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 188, in async_load
is_updated, config = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 207, in _load_config
config = load_yaml(self.path, Secrets(Path(self.hass.config.config_dir)))
File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 111, in load_yaml
return parse_yaml(conf_file, secrets)
File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 123, in parse_yaml
yaml.load(content, Loader=lambda stream: SafeLineLoader(stream, secrets))
File "/usr/local/lib/python3.9/site-packages/yaml/init.py", line 81, in load
return loader.get_single_data()
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
return self.construct_document(node)
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
data = self.construct_object(node)
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
data = constructor(self, node)
File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 253, in _ordered_dict
nodes = loader.construct_pairs(node)
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 155, in construct_pairs
value = self.construct_object(value_node, deep=deep)
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
data = constructor(self, node)
File "/config/custom_components/lovelace_gen/init.py", line 54, in _include_yaml
return loader._add_reference(load_yaml(fname, ldr.secrets, args=args), ldr, node)
File "/config/custom_components/lovelace_gen/init.py", line 32, in load_yaml
stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception

raise rewrite_traceback_stack(source=source)
File "/config/hki-base/base.yaml", line 1190, in top-level template code
{% for device in content.entities %}
TypeError: 'NoneType' object is not iterable

<img width="1153" alt="151883697-d8305f97-4e12-4ac5-a276-7490ca9d416a" src="https://user-images.githubusercontent.com/3034555/151901084-8ee919e9-9b0c-4b3d-b674-2ac4f1df8a57.png">

**Comment by dnestico** [comment]
Please see https://github.com/jimz011/homekit-infused/issues/124

**Comment by jimz011** [comment]
Remove the devices addon entirely from the view that you last worked on. Try to start, if it does restart slowly since the error is somewhere in between the devices addon.

You should also share code since the error alone gives too little information. But try the above first before sending code!
