### ISSUE TITLE
websocket lovelace_gen error 

### ISSUE THREAD

**Issue by Moosatronic** [jimz011/homekit-infused#138]
I've been trying to fix this error for long enough to no avail I thought I would raise it as an issue. Network-wise, my home-assistant is the docker version, and I access home assistant from outside my network via Nginx proxy manager. 

My log for the issue is below, but first i'll post the HKI-specific part of the error:

```
  File "/config/hki-base/base.yaml", line 145, in top-level template code
    - name: {{ config.title|tojson }}
```

and here is the full log below:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: hki-base/base.yaml:145
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:52:02 PM (10 occurrences)
Last logged: 7:53:51 PM

[140520061278240] Error handling message: Unknown error
[140520002629792] Error handling message: Unknown error
[140520043179408] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/usr/lib/python3.9/site-packages/homeassistant/components/lovelace/dashboard.py", line 188, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/lovelace/dashboard.py", line 207, in _load_config
    config = load_yaml(self.path, Secrets(Path(self.hass.config.config_dir)))
  File "/usr/lib/python3.9/site-packages/homeassistant/util/yaml/loader.py", line 111, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/lib/python3.9/site-packages/homeassistant/util/yaml/loader.py", line 123, in parse_yaml
    yaml.load(content, Loader=lambda stream: SafeLineLoader(stream, secrets))
  File "/usr/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.9/site-packages/homeassistant/util/yaml/loader.py", line 253, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, ldr.secrets, args=args), ldr, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/config/hki-base/base.yaml", line 145, in top-level template code
    - name: {{ config.title|tojson }}
  File "/usr/lib/python3.9/site-packages/jinja2/filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/usr/lib/python3.9/site-packages/jinja2/utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
```

I don't use any other dashboards. I simply was in the process of switching from HKI4 to 5 and quite quickly I came into this error. I have tried reinstalling hki-infused. It will always work the first time in a fresh install with the welcome message but right after I try to start putting my entities in views_config, i always  get this error and can't load the hki ui at all.

my view_config is below:

```
views: # NEVER REMOVE THIS LINE

# Default views (you can edit them!)

# Home
  home:
    title: greeting
    show_in_navbar: true
    show_in_menu: false
    icon: mdi:home
    addons:
      welcome_message:
        - title: hide
      favorites:
        - title: hide
          columns: 3

# Menu
  menu:
    title: Menu
    show_in_navbar: true
    show_in_menu: false
    subtitle: "[[[ return `HKI 5 v.${states['sensor.hki_current_version'].state}`; ]]]"
    icon: mdi:apps
    addons:
      favorites:
        - title: Favorites
      menu:
        - title: Menu

# Add your own views below this line!

# Lights (example)
  lights:
    title: Lights
    show_in_favorites: true
    icon: mdi:lightbulb
    addons:
     button:
      entities:
       - light.bedroom_lights
       - light.living_room_light_level_on_off
```
Probably made some stupid error, but in the off chance I didn't I thought I would post here.

**Comment by jimz011** [comment]
I hate to say it, but yes stupid error (but understandable). YAML is very strict on indentation. In this case you will need to work on your indentation. Know that when something gets indented in YAML it is ALWAYS 2 spaces, never 1 space, never 3.

In your case, you will want to edit the lines you have created and add a space (or multiple to a few of the lines)
```yaml
# Lights (example)
  lights:
    title: Lights
    show_in_favorites: true
    icon: mdi:lightbulb
    addons:
      button:
        entities:
          - light.bedroom_lights
          - light.living_room_light_level_on_off
```

Please be sure to compare this to your own view and look at what the differences are, they are very very subtle!

**Comment by Moosatronic** [comment]
I corrected my lights view config but it still resulted in the same websocket errors I described above. I've found that home assistant is normally good at catching formatting errors with the "check configuration" button, guess i need to be more careful. 

what I wrote: 
```
# Lights (example)
  lights:
    title: Lights
    show_in_favorites: true
    icon: mdi:lightbulb
    addons:
      button:
        entities:
          - light.bedroom_lights
          - light.living_room_light_level_on_off
```

**Comment by jimz011** [comment]
My apologies, I didn't read your code correctly the first time, the thing is, after defining an addon, you must use a list to define your stack/entities.

So you must do this:
```yaml
  lights:
    title: Lights
    show_in_favorites: true
    icon: mdi:lightbulb
    addons:
      button:
        - title: hide
          entities:
            - light.bedroom_lights
            - light.living_room_light_level_on_off

**Comment by jimz011** [comment]
You might want to check out the videos I have uploaded today:

https://www.youtube.com/playlist?list=PLezjWQmPsNpF9zNbWAXfm3mcnDwFYLdpT

**Comment by Moosatronic** [comment]
oooooh okay that seems like a more likely problem right there. guess it's just something to remember to do in HKI4.

**Comment by Moosatronic** [comment]
yeah now it's working fine, thank you for helpming me with this rookie mistake. Just wish home assistant's config checker could identify the specific part of the config that's the problem, i'm sure more than a few people might end up here with the same issue.

**Comment by jimz011** [comment]
Yeah, unfortunately it is because HKI uses lovelace_gen and since that is not something supported by default by HA it doesn't recognize the errors. It took me quite some time to understand it though. But the error is usually in the last 20 lines (both the file name and what the error is).

I don't expect anyone to understand them that is why the docs are pretty in depth, and is why I uploaded the videos today.

Glad you got it fixed now. Note that all addons work like that.
