### ISSUE TITLE
[ISSUE] When adjusting media play volume with popup card, HKI assumes brightness

### ISSUE THREAD

**Issue by noodlemctwoodle** [jimz011/homekit-infused#27]
**Describe the bug**
When you long press on a cast device added to the devices view, the popup card assumes you are adjusting the brightness.

**To Reproduce**
1. Go to 'Devices in HKI'
2. Click on 'Long press on a media entity such as a cast device'
3. The slider that is loaded assumes you are adjusting brightness

```
2020-03-12 16:30:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139666906365136] extra keys not allowed @ data['brightness']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 86, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1208, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['brightness']

```
**Expected behavior**
Popup-card should adjust the volume.

**Screenshots**
![image](https://user-images.githubusercontent.com/15075388/76544339-c3fd4100-647f-11ea-8418-99b02810f473.png)

**Current Running Home Assistant version:**
0.106.6

**Device HA running on and client device viewing lovelace:**
Intel NUC i3 7th gen and Google Pixel 4 XL

**Additional context**
HKI Version Beta 7

**Comment by jimz011** [comment]
Devices initially wasn't meant to put media player entities inside of. The popup card on that view was created for switches. But because people asked me to lift the switch only restriction it is possible to put other entities inside that view then just switches. The number of supported features depicts if it should show a switch or a slider. In this case your media player has more than 9 supported features thus it shows you a slider. I am reconsidering the popup cards for the devices view because of this, though I have roombased views planned for a future update which makes more sense when used the way you currently do.

**Comment by noodlemctwoodle** [comment]
I've moved all my media_player entities to the "Media" card for now anyway. 

Look forward to Room based views in the future. 

Is it worth adding to the docs what entities can be used in what HKI views? This may reduce the number of issues poeople raise issues when HKI 2.0 goes GA?

**Comment by jimz011** [comment]
Well that might be a good idea yes, though I will revise groups in the future which hopefully makes this unnecessary. Still working on rooms. Might take a while though as I am trying to fix the websocket errors first (it causes HKI to crash after visiting a bunch of views and it will say: Reload Lovelace) temporary fix is a refresh, but that isn’t the way it is supposed to work.

**Comment by jimz011** [comment]
The next update will have room based view support so this is no longer an issue!
