### ISSUE TITLE
[ISSUE]Installation failed

### ISSUE THREAD

**Issue by timmy0209** [jimz011/homekit-infused#62]
my homeassismant is installed in win10 through python，After I follow the steps to install homekit-infused, I can see the HKI in the sidebar, but when I click HKI, it will display unknown error。i can see Dwains Theme Dark (HKI Edition) in theme.

**Comment by jimz011** [comment]
Do you have Dwains Dashboard installed? If yes then either uninstall it or read up on Dwains documentation on how to run them simultaneously. It is supported, however I haven't documented it yet. Also some users reported that it isn't stable yet. So consider having both dashboards in an alpha stage.

**Comment by jimz011** [comment]
If you don't have dwains dashboard installed please send me some error logs and/or screenshots of what you do see. You can also join our discord channel if you prefer.

**Comment by timmy0209** [comment]
i haven‘t installed Dwains Dashboard。

![image](https://user-images.githubusercontent.com/54787369/101065162-c7b59280-35cf-11eb-8d4f-536f6f9e80a0.png)
![QQ图片20201204012744](https://user-images.githubusercontent.com/54787369/101065283-eb78d880-35cf-11eb-82d8-ddc218f634f2.png)

2020-12-04 01:22:30 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=24 from 2020-12-03 00:58:58.587765)
'cat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2020-12-04 01:22:43 ERROR (MainThread) [homeassistant.components.sensor] systemmonitor: Error on device update!
Traceback (most recent call last):
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity.py", line 466, in async_device_update
    await task
  File "c:\users\49207\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\systemmonitor\sensor.py", line 241, in update
    self._state = round(psutil.disk_usage(self.argument).used / 1024 ** 3, 1)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\deps\Python38\site-packages\psutil\__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\deps\Python38\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/'
2020-12-04 01:22:43 ERROR (SyncWorker_1) [homeassistant.components.command_line] Command failed: cat /sys/class/thermal/thermal_zone0/temp
2020-12-04 01:22:43 ERROR (MainThread) [homeassistant.components.sensor] systemmonitor: Error on device update!
Traceback (most recent call last):
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\helpers\entity.py", line 466, in async_device_update
    await task
  File "c:\users\49207\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\systemmonitor\sensor.py", line 243, in update
    self._state = round(psutil.disk_usage(self.argument).free / 1024 ** 3, 1)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\deps\Python38\site-packages\psutil\__init__.py", line 2015, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\deps\Python38\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/'
2020-12-04 01:22:43 ERROR (MainThread) [homeassistant.components.sensor] systemmonitor: Error on device update!

**Comment by jimz011** [comment]
Ah, I see what the problem is. It can not set up the sensors included with HKI because you are using Windows. Personally I'd never use Windows to run HA on as it imposes way too much problems (you will find a whole lot more in the future unrelated to this project if you continue to use Windows).
Ofcourse you can run whatever you want, however I would recommend you to run at least Linux (or use HassOS or a Home Assistant docker image, but again the docker image must not run on Windows either).

If you do plan to continue to use Windows for Home Assistant, there is one thing you can try:

- open the following file, `/packages/homekit_infused/hki_sensors.yaml` with your favorite text editor
- remove or comment out all the lines related to the system monitor (in this case line 87 to 112)
- save the file and restart Home Assistant, please report what it does for you now!

Let me know if this helps

**Comment by timmy0209** [comment]
its sitll not work。I wonder if there's something wrong with websocket_api，it shows 2020-12-04 09:30:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2547010037888] Error handling message: Unknown error。


2020-12-04 09:29:59 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=27 from 2020-12-04 01:26:22.624027)
2020-12-04 09:30:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2547010037888] Error handling message: Unknown error
Traceback (most recent call last):
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\websocket_api\decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\lovelace\websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\lovelace\websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\lovelace\dashboard.py", line 185, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "c:\users\49207\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\components\lovelace\dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 59, in load_yaml
    return parse_yaml(conf_file)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 70, in parse_yaml
    return yaml.load(content, Loader=SafeLineLoader) or OrderedDict()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 198, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 37, in load_yaml
    return loader.yaml.load(config_file, Loader=loader.SafeLineLoader) or OrderedDict()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 198, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 198, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 198, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 37, in load_yaml
    return loader.yaml.load(config_file, Loader=loader.SafeLineLoader) or OrderedDict()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 229, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\homeassistant\util\yaml\loader.py", line 198, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "C:\Users\49207\AppData\Roaming\.homeassistant\custom_components\lovelace_gen\__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 177, in get_source
    pieces = split_template_path(template)
  File "c:\users\49207\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 32, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: C:\Users\49207\AppData\Roaming\.homeassistant\homekit-infused\base\templates\header\notification-template.yaml
2020-12-04 09:30:19 ERROR (MainThread) [custom_components.hacs.factory] xMrVizzy/button-toolbar - GitHub returned 404 for https://api.github.com/repos/xMrVizzy/button-toolbar
2020-12-04 09:32:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.home_assistant_latest_version is taking over 10 seconds

**Comment by jimz011** [comment]
My project doesn't use the websocket api, so errors related to the websocket are not related to HKI. Honestly I'd say try HA on linux as Windows is a real pain in the behind. You will get these errors all the time with a lot of different components and it will be difficult to find the exact cause since Windows lack a bunch of dependencies. Windows often has problems with port forwarding and such.

I also unfortunately do not have sufficient experience with Python on Windows to give you a reliable answer to your question.
