### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by sharkyP** [jimz011/homekit-infused#66]
I'm seeing this error in my home assistant logs on the latest version, appears to be an issue in base.yaml
Running the latest docker image (2020.12.2) on an Intel NUC

```
Logger: homeassistant.components.websocket_api.http.connection
Source: homekit-infused/base.yaml:28
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 31 December 2020, 20:15:31 (4 occurrences)
Last logged: 31 December 2020, 20:15:32

[140287160525488] Error handling message: Unknown error
[140287158411568] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 185, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return parse_yaml(conf_file)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 73, in parse_yaml
    return yaml.load(content, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 54, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "/config/custom_components/lovelace_gen/__init__.py", line 32, in load_yaml
    stream = io.StringIO(jinja.get_template(fname).render({**args, "_global": llgen_config}))
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/config/homekit-infused/base.yaml", line 28, in top-level template code
    min_columns: {{ _global.view.min_columns|default('1') }}
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'view'
```

**Comment by jimz011** [comment]
Seems like either the user folder is missing some config (/homekit-infused/user/config/) or lovelace_gen is not installed/working properly. Another question I would have is, do you have Dwains Dashboard installed? If yes, then you should read up on his documentation on how to make both dashboards work together.

**Comment by sharkyP** [comment]
i'm not using Dwains dashboard, i have configured some of the stuff in user/config/ e.g. rooms and the alarm however not much further yet, i have lovelace_gen installed and latest stable version installed

Am I missing something in config?

**Comment by jimz011** [comment]
Ok I'll ask some more questions so we can get to the bottom of this.

1. Do you have a reference to lovelace_gen in your configuration.yaml? if yes then remove it
2. Did you comment anything out in the following file (homekit-infused/user/config/view_config.yaml). If yes then redownload the original file from this repo

**Comment by sharkyP** [comment]
no to both of those questions

**Comment by jimz011** [comment]
Well it seems that lovelace_gen can not find the specified `view` property (which happens to be in /homekit-infused/user/config/view_config.yaml). To me it seems like the word `view:` is commented, but well you said it isn't so that's rather odd.

May I ask on what and how you've installed Home Assistant? Also did you copy the exact folder structure from the repo? This is kind of important since the paths are hardcoded.

**Comment by sharkyP** [comment]
my view_config.yaml matches the latest release (i've made no changes there, as per below)
I'm running the HA docker image and have followed the readme and made no changes to paths/dir structure

```
# View Configuration File
view:
# This file will change the views properties

# Layout Card Columns,set the minimum and maximum of columns lovelace should make when viewing lovelace.
# It is advised to set the minimum to `1` (since that will look the best on a smartphone). The number of
# shown columns depends on the size of the browser.

# Columns
  min_columns: 1
  max_columns: 3
```

**Comment by jimz011** [comment]
Unfortunately for now I do not know what the problem is, I will keep a look out on this, however, if you want I can connect to your instance and take a look at it. I will also suggest asking on my discord channel, maybe someone has already encountered this problem in the past.

**Comment by jimz011** [comment]
Could you try something? Please try the file below and tell me what the logs tell you. Replace this file in /homekit-infused/base.yaml

[base.zip](https://github.com/jimz011/homekit-infused/files/5760389/base.zip)

Unpack the zip file and replace the existing base.yaml file.
